### ISSUE TITLE
Contao 4.4

### ISSUE THREAD

**Issue by csaeum** [1up-lab/contao-full-background-images#35]
Wann kommt die Version für Contao4

**Comment by operatorone** [comment]
Da würde ich mich auch sehr für interessieren :-)

**Comment by operatorone** [comment]
Gibt es hier schon Neuigkeiten?

**Comment by bytehead** [comment]
Bis jetzt ist noch kein Release (+ Releasedatum) für Contao 4 (mit Manager-Support) geplant.

**Comment by mapfei** [comment]
Gibt es denn irgendeine Krücke, um die Erweiterung in Version 4.5 ans laufen zu bekommen?

**Comment by bytehead** [comment]
Du musst es einfach von Hand installieren mit `composer require oneup/contao-full-background-images dev-master` und dann die Extension aktivieren in `AppKernel.php`.
