### ISSUE TITLE
Contao 5 compatibility

### ISSUE THREAD

**Issue by rustykowski** [1up-lab/contao-full-background-images#38]
Ich würde deine Erweiterung auch sehr gerne zusammen mit Contao 5 verwenden. Die composer.json verbietet das allerdings zur Zeit. Wie hoch wäre der Aufwand dafür?

**Comment by rustykowski** [comment]
Danke! Kann sein, dass ich es erst morgen schaffe …

**Comment by bytehead** [comment]
Kein Stress 🙃

**Comment by rustykowski** [comment]
Diesen Fehler erhalte ich in Contao 5.3.7 und PHP 8.3:

`request.CRITICAL: Uncaught PHP Exception Error: "Undefined constant "Oneup\ContaoFullBackgroundImagesBundle\TL_ROOT"" at Runner.php line 81 {"exception":"[object] (Error(code: 0): Undefined constant \"Oneup\\ContaoFullBackgroundImagesBundle\\TL_ROOT\" at /var/www/vhosts/.../vendor/oneup/contao-full-background-images/src/Runner.php:81)"}`

Außerdem erhalte ich noch einen Fehler beim Bearbeiten einer Root-Page, aber der kommt aus dem Core.

**Comment by bytehead** [comment]
Kannst du updaten und erneut testen?

**Comment by bytehead** [comment]
Kannst du nochmals updaten und testen?

**Comment by rustykowski** [comment]
Jetzt läuft alles einwandfrei, super!

**Comment by bytehead** [comment]
Top, dann tagge ich noch ein Release.

**Comment by bytehead** [comment]
See https://github.com/1up-lab/contao-full-background-images/releases/tag/3.1.0

**Comment by rustykowski** [comment]
Vielen Dank, David!
